#+author: conao3
#+date: <2019-01-31 Thu>

[[https://github.com/conao3/firebase-helper][https://img.shields.io/github/tag/conao3/firebase-helper.svg?style=flat-square]]
[[https://github.com/conao3/firebase-helper][https://img.shields.io/github/license/conao3/firebase-helper.svg?style=flat-square]]
[[https://github.com/conao3/github-header][https://files.conao3.com/github-header/gif/firebase-helper.gif]]

~firebase-helper~ is project hosting on google firebase.
- [[#install][Install]]
- [[#usage][Usage]]
- [[#developer-information][Developer information]]
  - [[#install-developer-tools][Install developer tools]]
  - [[#local-test][Local test]]
    - [[#localtest-notice][localtest NOTICE]]
    - [[#functions-test][Functions test]]
  - [[#deploy][Deploy]]
    - [[#clone][Clone]]
    - [[#fix-firebaserc][Fix .firebaserc]]
    - [[#deploy][Deploy]]
  - [[#reference][Reference]]
- [[#license][License]]
- [[#author][Author]]

* Install
You don't need install. This project is already deployed on google firebase.

* Usage
Access each url on browser, or ~curl~ it.
** hello
https://us-central1-conao3-helper.cloudfunctions.net/hello
#+begin_src bash
  curl https://us-central1-conao3-helper.cloudfunctions.net/hello
    Hello from Firebase!
#+end_src

** hello_args
https://us-central1-conao3-helper.cloudfunctions.net/hello_args/coano3
#+begin_src bash
  curl https://us-central1-conao3-helper.cloudfunctions.net/hello_args/conao3
    Hello from Firebase!conao3
#+end_src

https://us-central1-conao3-helper.cloudfunctions.net/hello_args/:name
- ~:name~ is string

** date
https://us-central1-conao3-helper.cloudfunctions.net/date
#+begin_src bash
  curl https://us-central1-conao3-helper.cloudfunctions.net/date
    2019-02-03T03:15:11+00:00
#+end_src

** shield_docker
*NOW UNAVAIRABLE in FREE FIREBASE ACCOUNT*

As free firebase account's function is not allowed accessing other api,
this function don't working.

It works only localhost :)

https://us-central1-conao3-helper.cloudfunctions.net/shield_docker/conao3/po4a/name
#+begin_src bash
  curl https://us-central1-conao3-helper.cloudfunctions.net/shield_docker/conao3/po4a/name
    <svg xmlns="http://www.w3.org/2000/svg" width="170" height="20">
    <g>
    <rect x="0" y="0" width="100%" height="100%" fill="#007ec6"></rect>
    <rect x="0" y="0" width="86" height="100%" fill="#555"></rect>
    </g>
    <g fill="#fff" font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="11">
    <text x="5" y="14">docker unknown</text>
    <text x="128" y="14" text-anchor="middle">unknown</text>
    </g>
    </svg>
#+end_src

https://us-central1-conao3-helper.cloudfunctions.net/shield_docker/:username/:imagename/:badgetype
- ~:username~ and ~:imagename~ use of [[https://microbadger.com/][MicroBadger]].
- ~badgetype~ is allowed below type
  - name
  - layers
  - size
  - version
  - pulls
  - stars

* Developer information
** Install developer tools
#+begin_src bash
  # firebase-tool initialize if you need
  npm install -g firebase-tools
  firebase login

  cd conao3-helper/functions
  npm install
#+end_src

** Local test
*** localtest NOTICE
When functions are tested locally, access to the database and
saving are done on the production data.

*** Functions test
cf: https://firebase.google.com/docs/functions/local-emulator

Open other terminal and run it to automate build TS.
#+begin_src bash
  cd firebase-helper/functions/
  ./node_modules/.bin/tsc --watch
#+end_src

Serve functinos on localhost.
#+begin_src bash
  firebase serve --only functions --port=9000
    === Serving from '/Users/conao/Develop/git/firebase-helper'...

    i  functions: Preparing to emulate functions.
    Warning: You're using Node.js v11.8.0 but Google Cloud Functions only supports v6.11.5.
    ✔  functions: hello: http://localhost:9000/conao3-helper/us-central1/hello
#+end_src

Access url on prompt.
#+begin_src bash
  curl http://localhost:9000/conao3-helper/us-central1/hello
    Hellow from Firebase!
#+end_src

** Deploy
If you want to deploy your firebase, clone, fix and deploy.

*** Clone
#+begin_src bash
  git clone https://github.com/conao3/firebase-helper

  cd firebase-helper/
#+end_src

*** Fix .firebaserc
Fix firebase project name in ~.firebaserc~.
#+begin_src diff
  diff --git a/.firebaserc b/.firebaserc
  index e1571d9..3c75a00 100644
  --- a/.firebaserc
  +++ b/.firebaserc
  @@ -1,5 +1,5 @@
   {
     "projects": {
  -    "default": "conao3-com"
  +    "default": "YOUR-FIREBASE-PROJECT"
     }
   }
#+end_src

*** Deploy
#+begin_src bash
  firebase deploy
#+end_src

** Reference
- [[https://console.firebase.google.com/][Firebase Console]]
- [[https://expressjs.com/en/4x/api.html#res][Express]]
  - [[https://expressjs.com/en/4x/api.html#req][Express Document - Request]]
  - [[https://expressjs.com/en/4x/api.html#res][Express Document - Response]]
- [[https://firebase.google.com/docs/guides/][Firebase]]
  - [[https://firebase.google.com/docs/functions/][Firebase Document - Cloud Functions]]
  - [[https://firebase.google.com/docs/reference/functions/][Firebase Reference - Functions]]
- [[https://cloud.google.com/docs/][Google Cloud Functions]]
  - [[https://cloud.google.com/functions/docs/][Google Cloud Functions Document - Functions]]

* License
The GNU Affero General Public License, version 3 (AGPL3)

Copyright (c) 2019 Naoya Yamashita (@conao3) - https://conao3.com

#+begin_quote
This program is free software: you can redistribute it and/or modify it
under the terms of the Affero GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or (at your
option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the Affero GNU General Public
License for more details.

You should have received a copy of the Affero GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
#+end_quote

* Author
Naoya Yamashita (@conao3)
