#+author: conao3
#+date: <2019-01-31 Thu>

[[https://github.com/conao3/firebase-conao3][https://img.shields.io/github/tag/conao3/firebase-conao3.svg?style=flat-square]]
[[https://github.com/conao3/firebase-conao3][https://img.shields.io/github/license/conao3/firebase-conao3.svg?style=flat-square]]
[[https://github.com/conao3/github-header][https://files.conao3.com/github-header/gif/firebase-conao3.gif]]

~firebase-conao3~ is project hosting on google firebase.
* Install
You don't need install. This project is already deployed on google firebase.

* Usage

* Deploy
If you want to deploy your firebase, clone , fix and deploy.

** Clone
#+begin_src bash
  git clone https://github.com/conao3/firebase-conao3

  cd firebase-conao3/
#+end_src

** Fix
Fix firebase project name in ~.firebaserc~.
#+begin_src diff
  diff --git a/.firebaserc b/.firebaserc
  index e1571d9..3c75a00 100644
  --- a/.firebaserc
  +++ b/.firebaserc
  @@ -1,5 +1,5 @@
   {
     "projects": {
  -    "default": "conao3-com"
  +    "default": "YOUR-FIREBASE-PROJECT"
     }
   }
#+end_src

** Deploy
#+begin_src bash
  # firebase-tool initialize if you need
  npm install -g firebase-tool
  firebase login

  firebase deploy
#+end_src

* License
The GNU Affero General Public License, version 3 (AGPL3)

Copyright (c) 2019 Naoya Yamashita (@conao3) - https://conao3.com

#+begin_quote
This program is free software: you can redistribute it and/or modify it
under the terms of the Affero GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or (at your
option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the Affero GNU General Public
License for more details.

You should have received a copy of the Affero GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
#+end_quote

* Author
Naoya Yamashita (@conao3)
