#+author: conao
#+date: <2019-01-31 Thu>

[[https://github.com/conao3/firebase-helper.ts][https://raw.githubusercontent.com/conao3/files/master/header/png/firebase-helper.ts.png]]
[[https://github.com/conao3/firebase-helper.ts/blob/master/LICENSE][https://img.shields.io/github/license/conao3/firebase-helper.ts.svg?style=flat-square]]
[[https://github.com/conao3/firebase-helper.ts/releases][https://img.shields.io/github/tag/conao3/firebase-helper.ts.svg?style=flat-square]]
[[https://travis-ci.org/conao3/firebase-helper.ts][https://img.shields.io/travis/conao3/firebase-helper.ts/master.svg?style=flat-square]]
[[https://app.codacy.com/project/conao3/firebase-helper.ts/dashboard][https://img.shields.io/codacy/grade/3be4830366a5413d9654c74653ad2dc5.svg?logo=codacy&style=flat-square]]
[[https://www.patreon.com/conao3][https://img.shields.io/badge/patreon-@conao3-orange.svg?logo=patreon&style=flat-square]]
[[https://twitter.com/conao_3][https://img.shields.io/badge/twitter-@conao__3-blue.svg?logo=twitter&style=flat-square]]
[[https://join.slack.com/t/conao3-support/shared_invite/enQtNTg2MTY0MjkzOTU0LTFjOTdhOTFiNTM2NmY5YTE5MTNlYzNiOTE2MTZlZWZkNDEzZmRhN2E0NjkwMWViZTZiYjA4MDUxYTUzNDZiNjY][https://img.shields.io/badge/chat-on_slack-blue.svg?logo=slack&style=flat-square]]

* Table of Contents
- [[#background][Background]]
- [[#license-terms][License Terms]]
- [[#install][Install]]
- [[#usage][Usage]]
  - [[#hello][hello]]
  - [[#hello_args][hello_args]]
  - [[#date][date]]
  - [[#github_header][github_header]]
  - [[#shield_docker][shield_docker]]
- [[#developer-information][Developer information]]
  - [[#install-developer-tools][Install developer tools]]
  - [[#local-test][Local test]]
    - [[#localtest-notice][localtest NOTICE]]
    - [[#functions-test][Functions test]]
  - [[#deploy][Deploy]]
    - [[#clone][Clone]]
    - [[#fix-firebaserc][Fix .firebaserc]]
    - [[#deploy][Deploy]]
- [[#information][Information]]
  - [[#reference][Reference]]
  - [[#donation][Donation]]
  - [[#community][Community]]
  - [[#contribution][Contribution]]
  - [[#license][License]]
  - [[#author][Author]]
  - [[#contributors][Contributors]]

* Background
~firebase-helper~ is project hosting on google firebase.

* License Terms
Display license such as [[#license][license]] section If you use this project API or code in your project.

* Install
You don't need install. This project is already deployed on google firebase.

* Usage
Access each url on browser, or ~curl~ it.
** hello
https://us-central1-conao3-helper.cloudfunctions.net/hello
#+begin_src bash
  curl https://us-central1-conao3-helper.cloudfunctions.net/hello
    Hello from Firebase!
#+end_src

** hello_args
https://us-central1-conao3-helper.cloudfunctions.net/hello_args/conao3
#+begin_src bash
  curl https://us-central1-conao3-helper.cloudfunctions.net/hello_args/conao3
    Hello from Firebase!conao3
#+end_src

https://us-central1-conao3-helper.cloudfunctions.net/hello_args/:name
- ~:name~ is string

** date
https://us-central1-conao3-helper.cloudfunctions.net/date
#+begin_src bash
  curl https://us-central1-conao3-helper.cloudfunctions.net/date
    2019-02-03T03:15:11+00:00
#+end_src

** github_header
[[https://us-central1-conao3-helper.cloudfunctions.net/github_header/firebase-helper.svg][https://us-central1-conao3-helper.cloudfunctions.net/github_header/firebase-helper.svg]]
Return header for GitHub.

https://us-central1-conao3-helper.cloudfunctions.net/github_header/firebase-helper.svg
#+begin_src bash
  curl http://localhost:9000/conao3-helper/us-central1/github_header/firebase-helper
    <svg xmlns="http://www.w3.org/2000/svg" width="1000" height="170">
    <style xmlns="http://www.w3.org/2000/svg" type="text/css">
    @import url('https://fonts.googleapis.com/css?family=Sarabun:100');
    text {font-size: 70px; font-family: 'Sarabun', sans-serif; font-weight: 100;}
    </style>
    <g>
    <rect x="0" y="0" width="100%" height="100%" fill="#222"></rect>
    </g>
    <g fill="#fff" font-family="Open Sans">
    <text x="90" y="120" font-size="50">firebase-helper</text>
    </g>
    </svg>
#+end_src

https://us-central1-conao3-helper.cloudfunctions.net/github_header/:header.svg
- ~:header~ is string

  If you use ~;/?:@&=+$-_!~*.,()#'~ in ~:header~, must be URL encoded.

  Fail ~decodeURIComponent~, or not specify argument, return svg with ~github-header~.

- urlquery
  - ~?:background~ is background color wuthout ~#~
  - ~?:forground~ is forground color withour ~#~

ex: https://us-central1-conao3-helper.cloudfunctions.net/github_header/conao3%2Ffirebase-helper.svg?forground=000&background=abc

** shield_docker
*NOW UNAVAIRABLE in FREE FIREBASE ACCOUNT*

As free firebase account's function is not allowed accessing other api,
this function don't working.

It works only localhost :)

https://us-central1-conao3-helper.cloudfunctions.net/shield_docker/conao3/po4a/name
#+begin_src bash
  curl https://us-central1-conao3-helper.cloudfunctions.net/shield_docker/conao3/po4a/name
    <svg xmlns="http://www.w3.org/2000/svg" width="170" height="20">
    <g>
    <rect x="0" y="0" width="100%" height="100%" fill="#007ec6"></rect>
    <rect x="0" y="0" width="86" height="100%" fill="#555"></rect>
    </g>
    <g fill="#fff" font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="11">
    <text x="5" y="14">docker unknown</text>
    <text x="128" y="14" text-anchor="middle">unknown</text>
    </g>
    </svg>
#+end_src

https://us-central1-conao3-helper.cloudfunctions.net/shield_docker/:username/:imagename/:badgetype
- ~:username~ and ~:imagename~ use of [[https://microbadger.com/][MicroBadger]].
- ~badgetype~ is allowed below type
  - name
  - layers
  - size
  - version
  - pulls
  - stars

* Developer information
** Install developer tools
#+begin_src bash
  # firebase-tool initialize if you need
  npm install -g firebase-tools
  firebase login

  cd conao3-helper/functions
  npm install
#+end_src

** Local test
*** localtest NOTICE
When functions are tested locally, access to the database and
saving are done on the production data.

*** Functions test
cf: https://firebase.google.com/docs/functions/local-emulator

Open other terminal and run it to automate build TS.
#+begin_src bash
  cd firebase-helper/functions/
  ./node_modules/.bin/tsc --watch
#+end_src

Serve functinos on localhost.
#+begin_src bash
  firebase serve --only functions --port=9000
    === Serving from '/Users/conao/Develop/git/firebase-helper'...

    i  functions: Preparing to emulate functions.
    Warning: You're using Node.js v11.8.0 but Google Cloud Functions only supports v6.11.5.
    ✔  functions: hello: http://localhost:9000/conao3-helper/us-central1/hello
#+end_src

Access url on prompt.
#+begin_src bash
  curl http://localhost:9000/conao3-helper/us-central1/hello
    Hellow from Firebase!
#+end_src

** Deploy
If you want to deploy your firebase, clone, fix and deploy.

*** Clone
#+begin_src bash
  git clone https://github.com/conao3/firebase-helper

  cd firebase-helper/
#+end_src

*** Fix .firebaserc
Fix firebase project name in ~.firebaserc~.
#+begin_src diff
  diff --git a/.firebaserc b/.firebaserc
  index e1571d9..3c75a00 100644
  --- a/.firebaserc
  +++ b/.firebaserc
  @@ -1,5 +1,5 @@
   {
     "projects": {
  -    "default": "conao3-com"
  +    "default": "YOUR-FIREBASE-PROJECT"
     }
   }
#+end_src

*** Deploy
#+begin_src bash
  firebase deploy
#+end_src

* Information
** Reference
- [[https://console.firebase.google.com/][Firebase Console]]
- [[https://expressjs.com/en/4x/api.html#res][Express]]
  - [[https://expressjs.com/en/4x/api.html#req][Express Document - Request]]
  - [[https://expressjs.com/en/4x/api.html#res][Express Document - Response]]
- [[https://firebase.google.com/docs/guides/][Firebase]]
  - [[https://firebase.google.com/docs/functions/][Firebase Document - Cloud Functions]]
  - [[https://firebase.google.com/docs/reference/functions/][Firebase Reference - Functions]]
- [[https://cloud.google.com/docs/][Google Cloud Functions]]
  - [[https://cloud.google.com/functions/docs/][Google Cloud Functions Document - Functions]]

** Donation
I love OSS and I am dreaming of working on it as *full-time* job.

*With your support*, I will be able to spend more time at OSS!

[[https://www.patreon.com/conao3][https://c5.patreon.com/external/logo/become_a_patron_button.png]]

** Community
All feedback and suggestions are welcome!

You can use github issues, but you can also use [[https://join.slack.com/t/conao3-support/shared_invite/enQtNTg2MTY0MjkzOTU0LTFjOTdhOTFiNTM2NmY5YTE5MTNlYzNiOTE2MTZlZWZkNDEzZmRhN2E0NjkwMWViZTZiYjA4MDUxYTUzNDZiNjY][Slack]]
if you want a more casual conversation.

** Contribution
Feel free to send PR!

** License
#+begin_example
  Affero General Public License Version 3 (AGPLv3)
  Copyright (c) Naoya Yamashita - https://conao3.com
  https://github.com/conao3/firebase-helper.ts/blob/master/LICENSE
#+end_example

** Author
- Naoya Yamashita ([[https://github.com/conao3][conao3]])

** Contributors
- Not yet... Now send PR and add your name!!
